#! /bin/bash

# Author Tim Craig  (TimCraig@Druai.com)  2020  
# No warranties implied or otherwise.

# Have colcon build specific packages (must be run at the top level of workspace
# Build, Install, Use up to 4 threads 

colcon build --symlink-install --parallel-workers 4 --packages-select $@

exit
